import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { connectDB } from "./lib/mongodb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
connectDB()
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
